### PR TITLE
Cycle grid martingale strategy ver.0.4b public edition

### PR DESCRIPTION
**Pull request by DogsTailFarmer**
Hi! During the last tests on Bitfinex, when two or more bots are launched simultaneously, everything freezes. Everything works on the Demo-OKEX . I assumed that this was due to additional functions, notification and writing to the sqlite3 database and isolated this code but result is the same - everything works on the test, everything hangs on Bitfinex. Perhaps colleagues from margin will be able to determine what the problem is.

Regard's, Jerry.

### CODE REVIEW

**Review by THuppke — CHANGES_REQUESTED** [review]
Hey Jerry, 
very nice job there!
Thanks for sharing all your effort here!

Could you put all your files into a sub-folder of the `margin_community_strategies` folder? That way people will know that it all belongs together.
Best,
Thoren!

**Review by THuppke — CHANGES_REQUESTED** [review]
Now it looks like there is a " " space in the directory name :sweat_smile: (in the beginning). Would be great if you could remove it

**Review by THuppke — APPROVED** [review]

**Comment by THuppke** [comment]
Looks good now! Thanks again for your contribution!

**Comment by DogsTailFarmer** [comment]
👌👍

**Comment by DogsTailFarmer** [comment]
Hi! Thoren, please edit the end of 

 "   Cycle grid martingale strategy ver.0.4b public edition remove ""  "
in the 
  MarginOpenSource  /  community-strategies 


and remove 'remove""'
Thank's, Jerry.


    On Monday, May 31, 2021, 7:15:48 PM GMT+3, Thoren Huppke ***@***.***> wrote:  
 
 


Looks good now! Thanks again for your contribution!

**Comment by THuppke** [comment]
Hey @DogsTailFarmer, which file do I need to change it in? Couldn't find that text with a quick search

**Comment by DogsTailFarmer** [comment]
Hi Thoren!Sorry, not worth the time.  I didn’t know that the commit comment goes to the repository table of contents.  I will correct it when updating.Regard's, Jerry. 7 июн. 2021 г. 09:55 пользователь Thoren Huppke ***@***.***> написал:
Hey @DogsTailFarmer, which file do I need to change it in? Couldn't find that text with a quick search

**Pull request merged**
